spring:

  datasource:
    driverClassName: org.h2.Driver
    password: Root
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  jpa:
#    this prop is to use data.sql
    defer-datasource-initialization: true
#    this prop is to use data.sql
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create